#include <iostream>
#include <iomanip>
#include <string>
#include <algorithm>  
#include <vector>
#include <limits>
#include <stdexcept>
#include <random> 

using std::cout;
using std::cin;
using std::endl;
using std::left;
using std::right;
using std::setw;
using std::setprecision;
using std::string;
using std::copy;
using std::vector;
using std::fixed;
using std::left;
using std::exception;